##### Copyright 2019 The TensorFlow Authors.

Licensed under the Apache License, Version 2.0 (the "License");

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Load a pandas.DataFrame

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/load_data/pandas_dataframe"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This tutorial provides an example of how to load pandas dataframes into a `tf.data.Dataset`.

This tutorials uses a small [dataset](https://archive.ics.uci.edu/ml/datasets/heart+Disease) provided by the Cleveland Clinic Foundation for Heart Disease. There are several hundred rows in the CSV. Each row describes a patient, and each column describes an attribute. We will use this information to predict whether a patient has heart disease, which in this dataset is a binary classification task.

## Read data using pandas

In [2]:
import pandas as pd
import tensorflow as tf

Download the csv file containing the heart dataset.

In [3]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/applied-dl/heart.csv')

 8192/13273 [=================>............] - ETA: 0s

16384/13273 [=====================================] - 0s 0us/step


Read the csv file using pandas.

In [4]:
df = pd.read_csv(csv_file)

In [5]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [6]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

Convert `thal` column which is an `object` in the dataframe to a discrete numerical value.

In [7]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

In [8]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

## Load data using `tf.data.Dataset`

Use `tf.data.Dataset.from_tensor_slices` to read the values from a pandas dataframe. 

One of the advantages of using `tf.data.Dataset` is it allows you to write simple, highly efficient data pipelines. Read the [loading data guide](https://www.tensorflow.org/guide/data) to find out more.

In [9]:
target = df.pop('target')

In [10]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [11]:
for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


Since a `pd.Series` implements the `__array__` protocol it can be used transparently nearly anywhere you would use a `np.array` or a `tf.Tensor`.

In [12]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

Shuffle and batch the dataset.

In [13]:
train_dataset = dataset.shuffle(len(df)).batch(1)

## Create and train a model

In [14]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [15]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



  1/303 [..............................] - ETA: 0s - loss: 2.2081e-14 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 3.9830 - accuracy: 0.6923    

 51/303 [====>.........................] - ETA: 0s - loss: 2.6183 - accuracy: 0.7843

 76/303 [======>.......................] - ETA: 0s - loss: 2.2892 - accuracy: 0.7500

101/303 [=========>....................] - ETA: 0s - loss: 2.0461 - accuracy: 0.7426

126/303 [===========>..................] - ETA: 0s - loss: 1.7747 - accuracy: 0.7302

152/303 [==============>...............] - ETA: 0s - loss: 1.6959 - accuracy: 0.7237

178/303 [================>.............] - ETA: 0s - loss: 1.6345 - accuracy: 0.7303

204/303 [===================>..........] - ETA: 0s - loss: 1.5722 - accuracy: 0.7206

230/303 [=====================>........] - ETA: 0s - loss: 1.4874 - accuracy: 0.7174

256/303 [========================>.....] - ETA: 0s - loss: 1.4758 - accuracy: 0.7109

282/303 [==========================>...] - ETA: 0s - loss: 1.5464 - accuracy: 0.6986

303/303 [==============================] - 1s 2ms/step - loss: 1.4957 - accuracy: 0.6997


Epoch 2/15


  1/303 [..............................] - ETA: 0s - loss: 0.0030 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 0.5943 - accuracy: 0.7692

 52/303 [====>.........................] - ETA: 0s - loss: 0.5433 - accuracy: 0.8269

 78/303 [======>.......................] - ETA: 0s - loss: 0.8186 - accuracy: 0.7949

104/303 [=========>....................] - ETA: 0s - loss: 0.7227 - accuracy: 0.7788

129/303 [===========>..................] - ETA: 0s - loss: 0.7274 - accuracy: 0.7829

155/303 [==============>...............] - ETA: 0s - loss: 0.7601 - accuracy: 0.7548

179/303 [================>.............] - ETA: 0s - loss: 0.7742 - accuracy: 0.7486

206/303 [===================>..........] - ETA: 0s - loss: 0.7905 - accuracy: 0.7524

232/303 [=====================>........] - ETA: 0s - loss: 0.7633 - accuracy: 0.7500

258/303 [========================>.....] - ETA: 0s - loss: 0.8255 - accuracy: 0.7287

283/303 [===========================>..] - ETA: 0s - loss: 0.8374 - accuracy: 0.7208

303/303 [==============================] - 1s 2ms/step - loss: 0.9019 - accuracy: 0.7063


Epoch 3/15


  1/303 [..............................] - ETA: 0s - loss: 9.5849e-04 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.4518 - accuracy: 0.8519    

 54/303 [====>.........................] - ETA: 0s - loss: 0.8869 - accuracy: 0.7222

 80/303 [======>.......................] - ETA: 0s - loss: 0.8724 - accuracy: 0.7000

106/303 [=========>....................] - ETA: 0s - loss: 0.8685 - accuracy: 0.6981

133/303 [============>.................] - ETA: 0s - loss: 0.8020 - accuracy: 0.7218

160/303 [==============>...............] - ETA: 0s - loss: 0.8494 - accuracy: 0.7125

184/303 [=================>............] - ETA: 0s - loss: 0.8697 - accuracy: 0.7228

209/303 [===================>..........] - ETA: 0s - loss: 0.8433 - accuracy: 0.7129

236/303 [======================>.......] - ETA: 0s - loss: 0.8569 - accuracy: 0.7119

262/303 [========================>.....] - ETA: 0s - loss: 0.8717 - accuracy: 0.7061

289/303 [===========================>..] - ETA: 0s - loss: 0.8322 - accuracy: 0.7163

303/303 [==============================] - 1s 2ms/step - loss: 0.8484 - accuracy: 0.7096


Epoch 4/15
  1/303 [..............................] - ETA: 0s - loss: 0.0093 - accuracy: 1.0000

 25/303 [=>............................] - ETA: 0s - loss: 0.8407 - accuracy: 0.6400

 51/303 [====>.........................] - ETA: 0s - loss: 0.7641 - accuracy: 0.7059

 77/303 [======>.......................] - ETA: 0s - loss: 0.6701 - accuracy: 0.6883

104/303 [=========>....................] - ETA: 0s - loss: 0.6952 - accuracy: 0.6923

130/303 [===========>..................] - ETA: 0s - loss: 0.6389 - accuracy: 0.7077

154/303 [==============>...............] - ETA: 0s - loss: 0.7000 - accuracy: 0.7143

178/303 [================>.............] - ETA: 0s - loss: 0.7541 - accuracy: 0.6910

203/303 [===================>..........] - ETA: 0s - loss: 0.7384 - accuracy: 0.6995

229/303 [=====================>........] - ETA: 0s - loss: 0.7033 - accuracy: 0.7118

255/303 [========================>.....] - ETA: 0s - loss: 0.7284 - accuracy: 0.7020

282/303 [==========================>...] - ETA: 0s - loss: 0.7448 - accuracy: 0.7021

303/303 [==============================] - 1s 2ms/step - loss: 0.7417 - accuracy: 0.7063


Epoch 5/15


  1/303 [..............................] - ETA: 0s - loss: 0.1613 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.5654 - accuracy: 0.8214

 55/303 [====>.........................] - ETA: 0s - loss: 0.7234 - accuracy: 0.7091

 82/303 [=======>......................] - ETA: 0s - loss: 0.6776 - accuracy: 0.7439

108/303 [=========>....................] - ETA: 0s - loss: 0.6947 - accuracy: 0.7130

133/303 [============>.................] - ETA: 0s - loss: 0.6976 - accuracy: 0.7218

158/303 [==============>...............] - ETA: 0s - loss: 0.6714 - accuracy: 0.7215

185/303 [=================>............] - ETA: 0s - loss: 0.6934 - accuracy: 0.7189

212/303 [===================>..........] - ETA: 0s - loss: 0.6923 - accuracy: 0.7075

239/303 [======================>.......] - ETA: 0s - loss: 0.6467 - accuracy: 0.7322

266/303 [=========================>....] - ETA: 0s - loss: 0.6516 - accuracy: 0.7293

294/303 [============================>.] - ETA: 0s - loss: 0.6487 - accuracy: 0.7279

303/303 [==============================] - 1s 2ms/step - loss: 0.6505 - accuracy: 0.7294


Epoch 6/15
  1/303 [..............................] - ETA: 0s - loss: 0.3915 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.6122 - accuracy: 0.7037

 54/303 [====>.........................] - ETA: 0s - loss: 0.5926 - accuracy: 0.7593

 81/303 [=======>......................] - ETA: 0s - loss: 0.5447 - accuracy: 0.7778

106/303 [=========>....................] - ETA: 0s - loss: 0.5524 - accuracy: 0.7453

133/303 [============>.................] - ETA: 0s - loss: 0.5423 - accuracy: 0.7444

160/303 [==============>...............] - ETA: 0s - loss: 0.5692 - accuracy: 0.7375

186/303 [=================>............] - ETA: 0s - loss: 0.5540 - accuracy: 0.7419

212/303 [===================>..........] - ETA: 0s - loss: 0.5757 - accuracy: 0.7358

238/303 [======================>.......] - ETA: 0s - loss: 0.5932 - accuracy: 0.7353

264/303 [=========================>....] - ETA: 0s - loss: 0.6000 - accuracy: 0.7311

291/303 [===========================>..] - ETA: 0s - loss: 0.5904 - accuracy: 0.7354

303/303 [==============================] - 1s 2ms/step - loss: 0.5874 - accuracy: 0.7360


Epoch 7/15
  1/303 [..............................] - ETA: 0s - loss: 0.2077 - accuracy: 1.0000

 29/303 [=>............................] - ETA: 0s - loss: 0.5760 - accuracy: 0.7586

 53/303 [====>.........................] - ETA: 0s - loss: 0.6620 - accuracy: 0.7736

 78/303 [======>.......................] - ETA: 0s - loss: 0.5419 - accuracy: 0.7821

103/303 [=========>....................] - ETA: 0s - loss: 0.5988 - accuracy: 0.7767

128/303 [===========>..................] - ETA: 0s - loss: 0.6102 - accuracy: 0.7656

153/303 [==============>...............] - ETA: 0s - loss: 0.5995 - accuracy: 0.7647

179/303 [================>.............] - ETA: 0s - loss: 0.5985 - accuracy: 0.7709

205/303 [===================>..........] - ETA: 0s - loss: 0.5808 - accuracy: 0.7805

230/303 [=====================>........] - ETA: 0s - loss: 0.5680 - accuracy: 0.7870

256/303 [========================>.....] - ETA: 0s - loss: 0.5689 - accuracy: 0.7812

282/303 [==========================>...] - ETA: 0s - loss: 0.5541 - accuracy: 0.7801

303/303 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7756


Epoch 8/15
  1/303 [..............................] - ETA: 0s - loss: 0.0082 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 0.3811 - accuracy: 0.8462

 51/303 [====>.........................] - ETA: 0s - loss: 0.5690 - accuracy: 0.7843

 77/303 [======>.......................] - ETA: 0s - loss: 0.5594 - accuracy: 0.7662

102/303 [=========>....................] - ETA: 0s - loss: 0.5429 - accuracy: 0.7549

126/303 [===========>..................] - ETA: 0s - loss: 0.5783 - accuracy: 0.7460

151/303 [=============>................] - ETA: 0s - loss: 0.5405 - accuracy: 0.7616

177/303 [================>.............] - ETA: 0s - loss: 0.5483 - accuracy: 0.7514

203/303 [===================>..........] - ETA: 0s - loss: 0.5323 - accuracy: 0.7635

229/303 [=====================>........] - ETA: 0s - loss: 0.5271 - accuracy: 0.7598

253/303 [========================>.....] - ETA: 0s - loss: 0.5219 - accuracy: 0.7589

279/303 [==========================>...] - ETA: 0s - loss: 0.5253 - accuracy: 0.7491

303/303 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7525


Epoch 9/15
  1/303 [..............................] - ETA: 0s - loss: 0.2066 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.5797 - accuracy: 0.7037

 53/303 [====>.........................] - ETA: 0s - loss: 0.5171 - accuracy: 0.6981

 79/303 [======>.......................] - ETA: 0s - loss: 0.4390 - accuracy: 0.7595

105/303 [=========>....................] - ETA: 0s - loss: 0.4188 - accuracy: 0.7524

130/303 [===========>..................] - ETA: 0s - loss: 0.4153 - accuracy: 0.7769

155/303 [==============>...............] - ETA: 0s - loss: 0.4220 - accuracy: 0.7677

181/303 [================>.............] - ETA: 0s - loss: 0.4091 - accuracy: 0.7790

207/303 [===================>..........] - ETA: 0s - loss: 0.4628 - accuracy: 0.7633

234/303 [======================>.......] - ETA: 0s - loss: 0.4794 - accuracy: 0.7607

261/303 [========================>.....] - ETA: 0s - loss: 0.4877 - accuracy: 0.7586

289/303 [===========================>..] - ETA: 0s - loss: 0.5151 - accuracy: 0.7439

303/303 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7492


Epoch 10/15
  1/303 [..............................] - ETA: 0s - loss: 0.0284 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.4419 - accuracy: 0.7407

 54/303 [====>.........................] - ETA: 0s - loss: 0.4467 - accuracy: 0.7407

 81/303 [=======>......................] - ETA: 0s - loss: 0.4614 - accuracy: 0.7407

107/303 [=========>....................] - ETA: 0s - loss: 0.4795 - accuracy: 0.7290

132/303 [============>.................] - ETA: 0s - loss: 0.5109 - accuracy: 0.7273

157/303 [==============>...............] - ETA: 0s - loss: 0.5091 - accuracy: 0.7325

183/303 [=================>............] - ETA: 0s - loss: 0.5036 - accuracy: 0.7486

210/303 [===================>..........] - ETA: 0s - loss: 0.5016 - accuracy: 0.7571

237/303 [======================>.......] - ETA: 0s - loss: 0.4977 - accuracy: 0.7637

264/303 [=========================>....] - ETA: 0s - loss: 0.5103 - accuracy: 0.7538

291/303 [===========================>..] - ETA: 0s - loss: 0.4841 - accuracy: 0.7698

303/303 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7690


Epoch 11/15
  1/303 [..............................] - ETA: 0s - loss: 1.5021 - accuracy: 0.0000e+00

 29/303 [=>............................] - ETA: 0s - loss: 0.6295 - accuracy: 0.6897    

 57/303 [====>.........................] - ETA: 0s - loss: 0.5909 - accuracy: 0.7544

 84/303 [=======>......................] - ETA: 0s - loss: 0.5732 - accuracy: 0.7262

110/303 [=========>....................] - ETA: 0s - loss: 0.5562 - accuracy: 0.7273

136/303 [============>.................] - ETA: 0s - loss: 0.5398 - accuracy: 0.7279

162/303 [===============>..............] - ETA: 0s - loss: 0.5162 - accuracy: 0.7407

188/303 [=================>............] - ETA: 0s - loss: 0.4880 - accuracy: 0.7500

215/303 [====================>.........] - ETA: 0s - loss: 0.4895 - accuracy: 0.7488

243/303 [=======================>......] - ETA: 0s - loss: 0.4838 - accuracy: 0.7572

270/303 [=========================>....] - ETA: 0s - loss: 0.4637 - accuracy: 0.7667

297/303 [============================>.] - ETA: 0s - loss: 0.4662 - accuracy: 0.7710

303/303 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7591


Epoch 12/15
  1/303 [..............................] - ETA: 0s - loss: 1.4999 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 1.0738 - accuracy: 0.7143    

 54/303 [====>.........................] - ETA: 0s - loss: 0.7472 - accuracy: 0.8148

 80/303 [======>.......................] - ETA: 0s - loss: 0.7279 - accuracy: 0.7750

107/303 [=========>....................] - ETA: 0s - loss: 0.6745 - accuracy: 0.7944

133/303 [============>.................] - ETA: 0s - loss: 0.5987 - accuracy: 0.8045

160/303 [==============>...............] - ETA: 0s - loss: 0.5568 - accuracy: 0.8062

186/303 [=================>............] - ETA: 0s - loss: 0.5158 - accuracy: 0.8172

212/303 [===================>..........] - ETA: 0s - loss: 0.5030 - accuracy: 0.8113

238/303 [======================>.......] - ETA: 0s - loss: 0.5079 - accuracy: 0.8151

265/303 [=========================>....] - ETA: 0s - loss: 0.5124 - accuracy: 0.8075

291/303 [===========================>..] - ETA: 0s - loss: 0.5235 - accuracy: 0.8007

303/303 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7954


Epoch 13/15
  1/303 [..............................] - ETA: 0s - loss: 0.1813 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.4147 - accuracy: 0.7778

 55/303 [====>.........................] - ETA: 0s - loss: 0.3378 - accuracy: 0.8364

 83/303 [=======>......................] - ETA: 0s - loss: 0.4141 - accuracy: 0.7952

111/303 [=========>....................] - ETA: 0s - loss: 0.3981 - accuracy: 0.8108

137/303 [============>.................] - ETA: 0s - loss: 0.4457 - accuracy: 0.7883

164/303 [===============>..............] - ETA: 0s - loss: 0.4614 - accuracy: 0.7866

191/303 [=================>............] - ETA: 0s - loss: 0.4800 - accuracy: 0.7696

218/303 [====================>.........] - ETA: 0s - loss: 0.4739 - accuracy: 0.7661

244/303 [=======================>......] - ETA: 0s - loss: 0.4745 - accuracy: 0.7582

269/303 [=========================>....] - ETA: 0s - loss: 0.4549 - accuracy: 0.7695

295/303 [============================>.] - ETA: 0s - loss: 0.4576 - accuracy: 0.7729

303/303 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7723


Epoch 14/15
  1/303 [..............................] - ETA: 0s - loss: 0.0205 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.4593 - accuracy: 0.7500

 55/303 [====>.........................] - ETA: 0s - loss: 0.3232 - accuracy: 0.8182

 81/303 [=======>......................] - ETA: 0s - loss: 0.2991 - accuracy: 0.8519

108/303 [=========>....................] - ETA: 0s - loss: 0.3481 - accuracy: 0.8148

135/303 [============>.................] - ETA: 0s - loss: 0.3502 - accuracy: 0.8148

162/303 [===============>..............] - ETA: 0s - loss: 0.3966 - accuracy: 0.8025

187/303 [=================>............] - ETA: 0s - loss: 0.4078 - accuracy: 0.7968

213/303 [====================>.........] - ETA: 0s - loss: 0.4011 - accuracy: 0.8028

239/303 [======================>.......] - ETA: 0s - loss: 0.4028 - accuracy: 0.8033

265/303 [=========================>....] - ETA: 0s - loss: 0.4270 - accuracy: 0.7962

291/303 [===========================>..] - ETA: 0s - loss: 0.4569 - accuracy: 0.7938

303/303 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7987


Epoch 15/15
  1/303 [..............................] - ETA: 0s - loss: 0.2432 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.2659 - accuracy: 0.8571

 55/303 [====>.........................] - ETA: 0s - loss: 0.4209 - accuracy: 0.8545

 81/303 [=======>......................] - ETA: 0s - loss: 0.3760 - accuracy: 0.8765

107/303 [=========>....................] - ETA: 0s - loss: 0.3651 - accuracy: 0.8692

133/303 [============>.................] - ETA: 0s - loss: 0.3780 - accuracy: 0.8421

160/303 [==============>...............] - ETA: 0s - loss: 0.3730 - accuracy: 0.8438

187/303 [=================>............] - ETA: 0s - loss: 0.3817 - accuracy: 0.8503

214/303 [====================>.........] - ETA: 0s - loss: 0.4073 - accuracy: 0.8271

241/303 [======================>.......] - ETA: 0s - loss: 0.4412 - accuracy: 0.8216

267/303 [=========================>....] - ETA: 0s - loss: 0.4538 - accuracy: 0.8165

293/303 [============================>.] - ETA: 0s - loss: 0.4586 - accuracy: 0.8123

303/303 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.8053


## Alternative to feature columns

Passing a dictionary as an input to a model is as easy as creating a matching dictionary of `tf.keras.layers.Input` layers, applying any pre-processing and stacking them up using the [functional api](../../guide/keras/functional.ipynb). You can use this as an alternative to [feature columns](../keras/feature_columns.ipynb).

In [16]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

The easiest way to preserve the column structure of a `pd.DataFrame` when used with `tf.data` is to convert the `pd.DataFrame` to a `dict`, and slice that dictionary.

In [17]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [18]:
for dict_slice in dict_slices.take(1):
  print (dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [19]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15


 1/19 [>.............................] - ETA: 0s - loss: 33.7216 - accuracy: 0.2500

19/19 [==============================] - 0s 3ms/step - loss: 26.7893 - accuracy: 0.2739


Epoch 2/15
 1/19 [>.............................] - ETA: 0s - loss: 17.8493 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 12.2734 - accuracy: 0.2739

19/19 [==============================] - 0s 3ms/step - loss: 12.2734 - accuracy: 0.2739


Epoch 3/15
 1/19 [>.............................] - ETA: 0s - loss: 4.3144 - accuracy: 0.5000

19/19 [==============================] - ETA: 0s - loss: 2.7571 - accuracy: 0.5083

19/19 [==============================] - 0s 3ms/step - loss: 2.7571 - accuracy: 0.5083


Epoch 4/15
 1/19 [>.............................] - ETA: 0s - loss: 2.1017 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 2.0496 - accuracy: 0.7162


Epoch 5/15
 1/19 [>.............................] - ETA: 0s - loss: 1.5927 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 1.7324 - accuracy: 0.6436


Epoch 6/15
 1/19 [>.............................] - ETA: 0s - loss: 1.3358 - accuracy: 0.6250

19/19 [==============================] - ETA: 0s - loss: 1.6612 - accuracy: 0.6238

19/19 [==============================] - 0s 3ms/step - loss: 1.6612 - accuracy: 0.6238


Epoch 7/15
 1/19 [>.............................] - ETA: 0s - loss: 1.3495 - accuracy: 0.6875

19/19 [==============================] - 0s 2ms/step - loss: 1.5567 - accuracy: 0.6469


Epoch 8/15
 1/19 [>.............................] - ETA: 0s - loss: 1.2511 - accuracy: 0.6875

19/19 [==============================] - 0s 2ms/step - loss: 1.4756 - accuracy: 0.6403


Epoch 9/15
 1/19 [>.............................] - ETA: 0s - loss: 1.1879 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 1.3848 - accuracy: 0.6535


Epoch 10/15
 1/19 [>.............................] - ETA: 0s - loss: 1.1161 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 1.2977 - accuracy: 0.6535


Epoch 11/15
 1/19 [>.............................] - ETA: 0s - loss: 1.0434 - accuracy: 0.6875

19/19 [==============================] - ETA: 0s - loss: 1.2133 - accuracy: 0.6601

19/19 [==============================] - 0s 3ms/step - loss: 1.2133 - accuracy: 0.6601


Epoch 12/15
 1/19 [>.............................] - ETA: 0s - loss: 0.9751 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 1.1288 - accuracy: 0.6667


Epoch 13/15
 1/19 [>.............................] - ETA: 0s - loss: 0.9052 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 1.0468 - accuracy: 0.6634


Epoch 14/15
 1/19 [>.............................] - ETA: 0s - loss: 0.8383 - accuracy: 0.6875

19/19 [==============================] - 0s 2ms/step - loss: 0.9671 - accuracy: 0.6799


Epoch 15/15
 1/19 [>.............................] - ETA: 0s - loss: 0.7731 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 0.8915 - accuracy: 0.6865
