##### Copyright 2018 The TensorFlow Authors.


In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Load text

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/load_data/text"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/load_data/text.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/text.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/load_data/text.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This tutorial provides an example of how to use `tf.data.TextLineDataset` to load examples from text files. `TextLineDataset` is designed to create a dataset from a text file, in which each example is a line of text from the original file. This is potentially useful for any text data that is primarily line-based (for example, poetry or error logs).

In this tutorial, we'll use three different English translations of the same work, Homer's Illiad, and train a model to identify the translator given a single line of text.

## Setup

In [2]:
import tensorflow as tf

import tensorflow_datasets as tfds
import os

The texts of the three translations are by:

 - [William Cowper](https://en.wikipedia.org/wiki/William_Cowper) — [text](https://storage.googleapis.com/download.tensorflow.org/data/illiad/cowper.txt)

 - [Edward, Earl of Derby](https://en.wikipedia.org/wiki/Edward_Smith-Stanley,_14th_Earl_of_Derby) — [text](https://storage.googleapis.com/download.tensorflow.org/data/illiad/derby.txt)

- [Samuel Butler](https://en.wikipedia.org/wiki/Samuel_Butler_%28novelist%29) — [text](https://storage.googleapis.com/download.tensorflow.org/data/illiad/butler.txt)

The text files used in this tutorial have undergone some typical preprocessing tasks, mostly removing stuff — document header and footer, line numbers, chapter titles. Download these lightly munged files locally.

In [3]:
DIRECTORY_URL = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
FILE_NAMES = ['cowper.txt', 'derby.txt', 'butler.txt']

for name in FILE_NAMES:
  text_dir = tf.keras.utils.get_file(name, origin=DIRECTORY_URL+name)
  
parent_dir = os.path.dirname(text_dir)

parent_dir

  8192/815980 [..............................] - ETA: 0s

819200/815980 [==============================] - 0s 0us/step


  8192/809730 [..............................] - ETA: 0s

811008/809730 [==============================] - 0s 0us/step


  8192/807992 [..............................] - ETA: 0s

811008/807992 [==============================] - 0s 0us/step


'/home/kbuilder/.keras/datasets'

## Load text into datasets

Iterate through the files, loading each one into its own dataset.

Each example needs to be individually labeled, so use `tf.data.Dataset.map` to apply a labeler function to each one. This will iterate over every example in the dataset, returning (`example, label`) pairs.

In [4]:
def labeler(example, index):
  return example, tf.cast(index, tf.int64)  

labeled_data_sets = []

for i, file_name in enumerate(FILE_NAMES):
  lines_dataset = tf.data.TextLineDataset(os.path.join(parent_dir, file_name))
  labeled_dataset = lines_dataset.map(lambda ex: labeler(ex, i))
  labeled_data_sets.append(labeled_dataset)

Combine these labeled datasets into a single dataset, and shuffle it.


In [5]:
BUFFER_SIZE = 50000
BATCH_SIZE = 64
TAKE_SIZE = 5000

In [6]:
all_labeled_data = labeled_data_sets[0]
for labeled_dataset in labeled_data_sets[1:]:
  all_labeled_data = all_labeled_data.concatenate(labeled_dataset)
  
all_labeled_data = all_labeled_data.shuffle(
    BUFFER_SIZE, reshuffle_each_iteration=False)

You can use `tf.data.Dataset.take` and `print` to see what the `(example, label)` pairs look like. The `numpy` property shows each Tensor's value.

In [7]:
for ex in all_labeled_data.take(5):
  print(ex)

(<tf.Tensor: shape=(), dtype=string, numpy=b'Bears on his breast, exulting; yet not long'>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b"Spontaneous; yet he gain'd not, though he sav'd,">, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'And Helen answered, "He is Ulysses, a man of great craft, son of'>, <tf.Tensor: shape=(), dtype=int64, numpy=2>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'At first against Achilles, but command'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'Jove cannot less than hate me, who hath twice'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


## Encode text lines as numbers

Machine learning models work on numbers, not words, so the string values need to be converted into lists of numbers. To do that, map each unique word to a unique integer.

### Build vocabulary

First, build a vocabulary by tokenizing the text into a collection of individual unique words. There are a few ways to do this in both TensorFlow and Python. For this tutorial:

1. Iterate over each example's `numpy` value.
2. Use `tfds.features.text.Tokenizer` to split it into tokens.
3. Collect these tokens into a Python set, to remove duplicates.
4. Get the size of the vocabulary for later use.

In [8]:
tokenizer = tfds.features.text.Tokenizer()

vocabulary_set = set()
for text_tensor, _ in all_labeled_data:
  some_tokens = tokenizer.tokenize(text_tensor.numpy())
  vocabulary_set.update(some_tokens)

vocab_size = len(vocabulary_set)
vocab_size

17178

### Encode examples

Create an encoder by passing the `vocabulary_set` to `tfds.features.text.TokenTextEncoder`. The encoder's `encode` method takes in a string of text and returns a list of integers.

In [9]:
encoder = tfds.features.text.TokenTextEncoder(vocabulary_set)

You can try this on a single line to see what the output looks like.

In [10]:
example_text = next(iter(all_labeled_data))[0].numpy()
print(example_text)

b'Bears on his breast, exulting; yet not long'


In [11]:
encoded_example = encoder.encode(example_text)
print(encoded_example)

[454, 6881, 16824, 15838, 14315, 13797, 14571, 8987]


Now run the encoder on the dataset by wrapping it in `tf.py_function` and  passing that to the dataset's `map` method.

In [12]:
def encode(text_tensor, label):
  encoded_text = encoder.encode(text_tensor.numpy())
  return encoded_text, label

You want to use `Dataset.map` to apply this function to each element of the dataset.  `Dataset.map` runs in graph mode.

* Graph tensors do not have a value. 
* In graph mode you can only use TensorFlow Ops and functions. 

So you can't `.map` this function directly: You need to wrap it in a `tf.py_function`. The `tf.py_function` will pass regular tensors (with a value and a `.numpy()` method to access it), to the wrapped python function.

In [13]:
def encode_map_fn(text, label):
  # py_func doesn't set the shape of the returned tensors.
  encoded_text, label = tf.py_function(encode, 
                                       inp=[text, label], 
                                       Tout=(tf.int64, tf.int64))

  # `tf.data.Datasets` work best if all components have a shape set
  #  so set the shapes manually: 
  encoded_text.set_shape([None])
  label.set_shape([])

  return encoded_text, label


all_encoded_data = all_labeled_data.map(encode_map_fn)

## Split the dataset into test and train batches

Use `tf.data.Dataset.take` and `tf.data.Dataset.skip` to create a small test dataset and a larger training set.

Before being passed into the model, the datasets need to be batched. Typically, the examples inside of a batch need to be the same size and shape. But, the examples in these datasets are not all the same size — each line of text had a different number of words. So use `tf.data.Dataset.padded_batch` (instead of `batch`) to pad the examples to the same size.

In [14]:
train_data = all_encoded_data.skip(TAKE_SIZE).shuffle(BUFFER_SIZE)
train_data = train_data.padded_batch(BATCH_SIZE)

test_data = all_encoded_data.take(TAKE_SIZE)
test_data = test_data.padded_batch(BATCH_SIZE)

Now, `test_data` and `train_data` are not collections of (`example, label`) pairs, but collections of batches. Each batch is a pair of (*many examples*, *many labels*) represented as arrays.

To illustrate:

In [15]:
sample_text, sample_labels = next(iter(test_data))

sample_text[0], sample_labels[0]

(<tf.Tensor: shape=(15,), dtype=int64, numpy=
 array([  454,  6881, 16824, 15838, 14315, 13797, 14571,  8987,     0,
            0,     0,     0,     0,     0,     0])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>)

Since we have introduced a new token encoding (the zero used for padding), the vocabulary size has increased by one.

In [16]:
vocab_size += 1

## Build the model


In [17]:
model = tf.keras.Sequential()

The first layer converts integer representations to dense vector embeddings. See the [word embeddings tutorial](../text/word_embeddings.ipynb) or more details. 

In [18]:
model.add(tf.keras.layers.Embedding(vocab_size, 64))

The next layer is a [Long Short-Term Memory](http://colah.github.io/posts/2015-08-Understanding-LSTMs/) layer, which lets the model understand words in their context with other words. A bidirectional wrapper on the LSTM helps it to learn about the datapoints in relationship to the datapoints that came before it and after it.

In [19]:
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))

Finally we'll have a series of one or more densely connected layers, with the last one being the output layer. The output layer produces a probability for all the labels. The one with the highest probability is the models prediction of an example's label.

In [20]:
# One or more dense layers.
# Edit the list in the `for` line to experiment with layer sizes.
for units in [64, 64]:
  model.add(tf.keras.layers.Dense(units, activation='relu'))

# Output layer. The first argument is the number of labels.
model.add(tf.keras.layers.Dense(3))

Finally, compile the model. For a softmax categorization model, use `sparse_categorical_crossentropy` as the loss function. You can try other optimizers, but `adam` is very common.

In [21]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

## Train the model

This model running on this data produces decent results (about 83%).

In [22]:
model.fit(train_data, epochs=3, validation_data=test_data)

Epoch 1/3


      1/Unknown - 0s 14us/step - loss: 1.0968 - accuracy: 0.4531

      5/Unknown - 0s 10ms/step - loss: 1.0882 - accuracy: 0.3938

     11/Unknown - 0s 10ms/step - loss: 1.0701 - accuracy: 0.3920

     17/Unknown - 0s 9ms/step - loss: 1.0404 - accuracy: 0.3869 

     23/Unknown - 0s 9ms/step - loss: 1.0086 - accuracy: 0.4022

     29/Unknown - 0s 9ms/step - loss: 0.9836 - accuracy: 0.4370

     36/Unknown - 0s 9ms/step - loss: 0.9530 - accuracy: 0.4722

     42/Unknown - 0s 9ms/step - loss: 0.9206 - accuracy: 0.4944

     48/Unknown - 0s 9ms/step - loss: 0.8967 - accuracy: 0.5039

     54/Unknown - 0s 9ms/step - loss: 0.8761 - accuracy: 0.5116

     60/Unknown - 1s 9ms/step - loss: 0.8597 - accuracy: 0.5172

     66/Unknown - 1s 9ms/step - loss: 0.8398 - accuracy: 0.5272

     72/Unknown - 1s 9ms/step - loss: 0.8229 - accuracy: 0.5358

     78/Unknown - 1s 9ms/step - loss: 0.8100 - accuracy: 0.5435

     84/Unknown - 1s 9ms/step - loss: 0.7987 - accuracy: 0.5500

     90/Unknown - 1s 9ms/step - loss: 0.7857 - accuracy: 0.5568

     96/Unknown - 1s 9ms/step - loss: 0.7801 - accuracy: 0.5614

    103/Unknown - 1s 9ms/step - loss: 0.7698 - accuracy: 0.5669

    109/Unknown - 1s 9ms/step - loss: 0.7628 - accuracy: 0.5708

    115/Unknown - 1s 9ms/step - loss: 0.7600 - accuracy: 0.5727

    121/Unknown - 1s 9ms/step - loss: 0.7550 - accuracy: 0.5780

    127/Unknown - 1s 9ms/step - loss: 0.7466 - accuracy: 0.5851

    133/Unknown - 1s 9ms/step - loss: 0.7385 - accuracy: 0.5919

    139/Unknown - 1s 9ms/step - loss: 0.7335 - accuracy: 0.5953

    145/Unknown - 1s 9ms/step - loss: 0.7267 - accuracy: 0.5998

    151/Unknown - 1s 9ms/step - loss: 0.7226 - accuracy: 0.6038

    157/Unknown - 1s 9ms/step - loss: 0.7185 - accuracy: 0.6077

    163/Unknown - 1s 9ms/step - loss: 0.7137 - accuracy: 0.6111

    169/Unknown - 1s 9ms/step - loss: 0.7093 - accuracy: 0.6146

    175/Unknown - 2s 9ms/step - loss: 0.7044 - accuracy: 0.6179

    181/Unknown - 2s 9ms/step - loss: 0.7004 - accuracy: 0.6203

    187/Unknown - 2s 9ms/step - loss: 0.6953 - accuracy: 0.6249

    193/Unknown - 2s 9ms/step - loss: 0.6914 - accuracy: 0.6281

    199/Unknown - 2s 9ms/step - loss: 0.6876 - accuracy: 0.6314

    205/Unknown - 2s 9ms/step - loss: 0.6835 - accuracy: 0.6348

    211/Unknown - 2s 9ms/step - loss: 0.6806 - accuracy: 0.6363

    217/Unknown - 2s 9ms/step - loss: 0.6775 - accuracy: 0.6390

    223/Unknown - 2s 9ms/step - loss: 0.6755 - accuracy: 0.6408

    229/Unknown - 2s 9ms/step - loss: 0.6728 - accuracy: 0.6434

    235/Unknown - 2s 9ms/step - loss: 0.6688 - accuracy: 0.6457

    241/Unknown - 2s 9ms/step - loss: 0.6667 - accuracy: 0.6472

    247/Unknown - 2s 9ms/step - loss: 0.6626 - accuracy: 0.6508

    253/Unknown - 2s 9ms/step - loss: 0.6596 - accuracy: 0.6530

    259/Unknown - 2s 9ms/step - loss: 0.6562 - accuracy: 0.6549

    265/Unknown - 2s 9ms/step - loss: 0.6539 - accuracy: 0.6567

    271/Unknown - 2s 9ms/step - loss: 0.6501 - accuracy: 0.6591

    277/Unknown - 2s 9ms/step - loss: 0.6480 - accuracy: 0.6608

    283/Unknown - 3s 9ms/step - loss: 0.6449 - accuracy: 0.6632

    289/Unknown - 3s 9ms/step - loss: 0.6409 - accuracy: 0.6664

    295/Unknown - 3s 9ms/step - loss: 0.6394 - accuracy: 0.6680

    301/Unknown - 3s 9ms/step - loss: 0.6377 - accuracy: 0.6692

    307/Unknown - 3s 9ms/step - loss: 0.6345 - accuracy: 0.6718

    313/Unknown - 3s 9ms/step - loss: 0.6319 - accuracy: 0.6741

    319/Unknown - 3s 9ms/step - loss: 0.6295 - accuracy: 0.6755

    325/Unknown - 3s 9ms/step - loss: 0.6272 - accuracy: 0.6780

    331/Unknown - 3s 9ms/step - loss: 0.6249 - accuracy: 0.6794

    337/Unknown - 3s 9ms/step - loss: 0.6229 - accuracy: 0.6804

    343/Unknown - 3s 9ms/step - loss: 0.6209 - accuracy: 0.6822

    349/Unknown - 3s 9ms/step - loss: 0.6186 - accuracy: 0.6838

    355/Unknown - 3s 9ms/step - loss: 0.6168 - accuracy: 0.6849

    361/Unknown - 3s 9ms/step - loss: 0.6147 - accuracy: 0.6862

    367/Unknown - 3s 9ms/step - loss: 0.6121 - accuracy: 0.6881

    373/Unknown - 3s 9ms/step - loss: 0.6098 - accuracy: 0.6898

    379/Unknown - 3s 9ms/step - loss: 0.6080 - accuracy: 0.6911

    385/Unknown - 3s 9ms/step - loss: 0.6052 - accuracy: 0.6931

    391/Unknown - 4s 9ms/step - loss: 0.6026 - accuracy: 0.6944

    397/Unknown - 4s 9ms/step - loss: 0.6004 - accuracy: 0.6963

    403/Unknown - 4s 9ms/step - loss: 0.5977 - accuracy: 0.6980

    409/Unknown - 4s 9ms/step - loss: 0.5962 - accuracy: 0.6993

    415/Unknown - 4s 9ms/step - loss: 0.5946 - accuracy: 0.7006

    421/Unknown - 4s 9ms/step - loss: 0.5928 - accuracy: 0.7018

    427/Unknown - 4s 9ms/step - loss: 0.5906 - accuracy: 0.7032

    433/Unknown - 4s 9ms/step - loss: 0.5890 - accuracy: 0.7042

    439/Unknown - 4s 9ms/step - loss: 0.5866 - accuracy: 0.7059

    445/Unknown - 4s 9ms/step - loss: 0.5851 - accuracy: 0.7071

    451/Unknown - 4s 9ms/step - loss: 0.5836 - accuracy: 0.7083

    457/Unknown - 4s 9ms/step - loss: 0.5818 - accuracy: 0.7092

    463/Unknown - 4s 9ms/step - loss: 0.5805 - accuracy: 0.7102

    469/Unknown - 4s 9ms/step - loss: 0.5788 - accuracy: 0.7114

    475/Unknown - 4s 9ms/step - loss: 0.5764 - accuracy: 0.7126

    481/Unknown - 4s 9ms/step - loss: 0.5743 - accuracy: 0.7139

    487/Unknown - 4s 9ms/step - loss: 0.5726 - accuracy: 0.7149

    493/Unknown - 4s 9ms/step - loss: 0.5707 - accuracy: 0.7162

    499/Unknown - 4s 9ms/step - loss: 0.5689 - accuracy: 0.7171

    505/Unknown - 5s 9ms/step - loss: 0.5668 - accuracy: 0.7185

    511/Unknown - 5s 9ms/step - loss: 0.5644 - accuracy: 0.7200

    517/Unknown - 5s 9ms/step - loss: 0.5636 - accuracy: 0.7207

    523/Unknown - 5s 9ms/step - loss: 0.5614 - accuracy: 0.7223

    529/Unknown - 5s 9ms/step - loss: 0.5596 - accuracy: 0.7236

    535/Unknown - 5s 9ms/step - loss: 0.5576 - accuracy: 0.7247

    541/Unknown - 5s 9ms/step - loss: 0.5564 - accuracy: 0.7253

    547/Unknown - 5s 9ms/step - loss: 0.5551 - accuracy: 0.7261

    553/Unknown - 5s 9ms/step - loss: 0.5540 - accuracy: 0.7268

    559/Unknown - 5s 9ms/step - loss: 0.5528 - accuracy: 0.7276

    565/Unknown - 5s 9ms/step - loss: 0.5513 - accuracy: 0.7283

    571/Unknown - 5s 9ms/step - loss: 0.5496 - accuracy: 0.7291

    577/Unknown - 5s 9ms/step - loss: 0.5481 - accuracy: 0.7300

    583/Unknown - 5s 9ms/step - loss: 0.5464 - accuracy: 0.7310

    589/Unknown - 5s 9ms/step - loss: 0.5446 - accuracy: 0.7319

    595/Unknown - 5s 9ms/step - loss: 0.5435 - accuracy: 0.7327

    601/Unknown - 5s 9ms/step - loss: 0.5426 - accuracy: 0.7334

    606/Unknown - 5s 9ms/step - loss: 0.5416 - accuracy: 0.7340

    612/Unknown - 6s 9ms/step - loss: 0.5402 - accuracy: 0.7347

    618/Unknown - 6s 9ms/step - loss: 0.5390 - accuracy: 0.7355

    624/Unknown - 6s 9ms/step - loss: 0.5373 - accuracy: 0.7366

    630/Unknown - 6s 9ms/step - loss: 0.5360 - accuracy: 0.7374

    636/Unknown - 6s 9ms/step - loss: 0.5350 - accuracy: 0.7380

    642/Unknown - 6s 9ms/step - loss: 0.5342 - accuracy: 0.7383

    648/Unknown - 6s 9ms/step - loss: 0.5330 - accuracy: 0.7389

    654/Unknown - 6s 9ms/step - loss: 0.5319 - accuracy: 0.7394

    660/Unknown - 6s 9ms/step - loss: 0.5308 - accuracy: 0.7400

    666/Unknown - 6s 9ms/step - loss: 0.5294 - accuracy: 0.7409

    672/Unknown - 6s 9ms/step - loss: 0.5284 - accuracy: 0.7415

    678/Unknown - 6s 9ms/step - loss: 0.5273 - accuracy: 0.7421

    684/Unknown - 6s 9ms/step - loss: 0.5260 - accuracy: 0.7427

    690/Unknown - 6s 9ms/step - loss: 0.5247 - accuracy: 0.7434

    696/Unknown - 6s 9ms/step - loss: 0.5235 - accuracy: 0.7441

697/697 [==============================] - 10s 14ms/step - loss: 0.5233 - accuracy: 0.7442 - val_loss: 0.3920 - val_accuracy: 0.8244


Epoch 2/3


  1/697 [..............................] - ETA: 0s - loss: 0.2746 - accuracy: 0.8750

  7/697 [..............................] - ETA: 4s - loss: 0.2685 - accuracy: 0.8705

 13/697 [..............................] - ETA: 5s - loss: 0.2648 - accuracy: 0.8846

 19/697 [..............................] - ETA: 5s - loss: 0.2612 - accuracy: 0.8882

 25/697 [>.............................] - ETA: 5s - loss: 0.2703 - accuracy: 0.8863

 31/697 [>.............................] - ETA: 5s - loss: 0.2689 - accuracy: 0.8856

 37/697 [>.............................] - ETA: 5s - loss: 0.2745 - accuracy: 0.8809

 43/697 [>.............................] - ETA: 5s - loss: 0.2771 - accuracy: 0.8826

 50/697 [=>............................] - ETA: 5s - loss: 0.2816 - accuracy: 0.8813

 56/697 [=>............................] - ETA: 5s - loss: 0.2825 - accuracy: 0.8823

 62/697 [=>............................] - ETA: 5s - loss: 0.2887 - accuracy: 0.8800

 68/697 [=>............................] - ETA: 5s - loss: 0.2891 - accuracy: 0.8812

 74/697 [==>...........................] - ETA: 5s - loss: 0.2894 - accuracy: 0.8813

 80/697 [==>...........................] - ETA: 5s - loss: 0.2872 - accuracy: 0.8822

 86/697 [==>...........................] - ETA: 5s - loss: 0.2874 - accuracy: 0.8824

 92/697 [==>...........................] - ETA: 5s - loss: 0.2886 - accuracy: 0.8815

 98/697 [===>..........................] - ETA: 5s - loss: 0.2882 - accuracy: 0.8811

105/697 [===>..........................] - ETA: 5s - loss: 0.2864 - accuracy: 0.8824

111/697 [===>..........................] - ETA: 5s - loss: 0.2884 - accuracy: 0.8813

117/697 [====>.........................] - ETA: 4s - loss: 0.2871 - accuracy: 0.8821

124/697 [====>.........................] - ETA: 4s - loss: 0.2842 - accuracy: 0.8837

130/697 [====>.........................] - ETA: 4s - loss: 0.2866 - accuracy: 0.8826

136/697 [====>.........................] - ETA: 4s - loss: 0.2873 - accuracy: 0.8827

142/697 [=====>........................] - ETA: 4s - loss: 0.2890 - accuracy: 0.8819

148/697 [=====>........................] - ETA: 4s - loss: 0.2882 - accuracy: 0.8823

154/697 [=====>........................] - ETA: 4s - loss: 0.2882 - accuracy: 0.8814

160/697 [=====>........................] - ETA: 4s - loss: 0.2875 - accuracy: 0.8821

166/697 [======>.......................] - ETA: 4s - loss: 0.2881 - accuracy: 0.8814

172/697 [======>.......................] - ETA: 4s - loss: 0.2891 - accuracy: 0.8813

178/697 [======>.......................] - ETA: 4s - loss: 0.2910 - accuracy: 0.8805

184/697 [======>.......................] - ETA: 4s - loss: 0.2936 - accuracy: 0.8792

190/697 [=======>......................] - ETA: 4s - loss: 0.2947 - accuracy: 0.8789

196/697 [=======>......................] - ETA: 4s - loss: 0.2947 - accuracy: 0.8787

202/697 [=======>......................] - ETA: 4s - loss: 0.2952 - accuracy: 0.8782

208/697 [=======>......................] - ETA: 4s - loss: 0.2946 - accuracy: 0.8788

214/697 [========>.....................] - ETA: 4s - loss: 0.2961 - accuracy: 0.8785

220/697 [========>.....................] - ETA: 4s - loss: 0.2961 - accuracy: 0.8782

226/697 [========>.....................] - ETA: 4s - loss: 0.2961 - accuracy: 0.8784

232/697 [========>.....................] - ETA: 4s - loss: 0.2971 - accuracy: 0.8778

238/697 [=========>....................] - ETA: 3s - loss: 0.2972 - accuracy: 0.8779

244/697 [=========>....................] - ETA: 3s - loss: 0.2966 - accuracy: 0.8781

250/697 [=========>....................] - ETA: 3s - loss: 0.2959 - accuracy: 0.8781

256/697 [==========>...................] - ETA: 3s - loss: 0.2966 - accuracy: 0.8773

262/697 [==========>...................] - ETA: 3s - loss: 0.2965 - accuracy: 0.8774

268/697 [==========>...................] - ETA: 3s - loss: 0.2974 - accuracy: 0.8768

274/697 [==========>...................] - ETA: 3s - loss: 0.2968 - accuracy: 0.8771

280/697 [===========>..................] - ETA: 3s - loss: 0.2972 - accuracy: 0.8763

286/697 [===========>..................] - ETA: 3s - loss: 0.2972 - accuracy: 0.8764

292/697 [===========>..................] - ETA: 3s - loss: 0.2976 - accuracy: 0.8762

299/697 [===========>..................] - ETA: 3s - loss: 0.2972 - accuracy: 0.8766

306/697 [============>.................] - ETA: 3s - loss: 0.2967 - accuracy: 0.8765

313/697 [============>.................] - ETA: 3s - loss: 0.2969 - accuracy: 0.8759

320/697 [============>.................] - ETA: 3s - loss: 0.2966 - accuracy: 0.8756

326/697 [=============>................] - ETA: 3s - loss: 0.2967 - accuracy: 0.8755

332/697 [=============>................] - ETA: 3s - loss: 0.2966 - accuracy: 0.8750

338/697 [=============>................] - ETA: 3s - loss: 0.2963 - accuracy: 0.8751

344/697 [=============>................] - ETA: 3s - loss: 0.2966 - accuracy: 0.8747

350/697 [==============>...............] - ETA: 3s - loss: 0.2964 - accuracy: 0.8749

356/697 [==============>...............] - ETA: 2s - loss: 0.2968 - accuracy: 0.8749

362/697 [==============>...............] - ETA: 2s - loss: 0.2969 - accuracy: 0.8746

368/697 [==============>...............] - ETA: 2s - loss: 0.2962 - accuracy: 0.8745

374/697 [===============>..............] - ETA: 2s - loss: 0.2958 - accuracy: 0.8746

380/697 [===============>..............] - ETA: 2s - loss: 0.2956 - accuracy: 0.8746

386/697 [===============>..............] - ETA: 2s - loss: 0.2957 - accuracy: 0.8744

392/697 [===============>..............] - ETA: 2s - loss: 0.2958 - accuracy: 0.8740

398/697 [================>.............] - ETA: 2s - loss: 0.2963 - accuracy: 0.8741

404/697 [================>.............] - ETA: 2s - loss: 0.2965 - accuracy: 0.8742

410/697 [================>.............] - ETA: 2s - loss: 0.2968 - accuracy: 0.8740

417/697 [================>.............] - ETA: 2s - loss: 0.2968 - accuracy: 0.8740

423/697 [=================>............] - ETA: 2s - loss: 0.2972 - accuracy: 0.8737

429/697 [=================>............] - ETA: 2s - loss: 0.2975 - accuracy: 0.8735

435/697 [=================>............] - ETA: 2s - loss: 0.2978 - accuracy: 0.8732

441/697 [=================>............] - ETA: 2s - loss: 0.2971 - accuracy: 0.8734

447/697 [==================>...........] - ETA: 2s - loss: 0.2976 - accuracy: 0.8730

453/697 [==================>...........] - ETA: 2s - loss: 0.2978 - accuracy: 0.8732

459/697 [==================>...........] - ETA: 2s - loss: 0.2983 - accuracy: 0.8729

465/697 [===================>..........] - ETA: 2s - loss: 0.2982 - accuracy: 0.8729

471/697 [===================>..........] - ETA: 1s - loss: 0.2981 - accuracy: 0.8729

477/697 [===================>..........] - ETA: 1s - loss: 0.2975 - accuracy: 0.8732

483/697 [===================>..........] - ETA: 1s - loss: 0.2981 - accuracy: 0.8727

489/697 [====================>.........] - ETA: 1s - loss: 0.2984 - accuracy: 0.8724

495/697 [====================>.........] - ETA: 1s - loss: 0.2983 - accuracy: 0.8723

501/697 [====================>.........] - ETA: 1s - loss: 0.2985 - accuracy: 0.8721

507/697 [====================>.........] - ETA: 1s - loss: 0.2981 - accuracy: 0.8723

513/697 [=====================>........] - ETA: 1s - loss: 0.2982 - accuracy: 0.8724

519/697 [=====================>........] - ETA: 1s - loss: 0.2980 - accuracy: 0.8724

525/697 [=====================>........] - ETA: 1s - loss: 0.2989 - accuracy: 0.8721

531/697 [=====================>........] - ETA: 1s - loss: 0.2991 - accuracy: 0.8721

537/697 [======================>.......] - ETA: 1s - loss: 0.2992 - accuracy: 0.8721

543/697 [======================>.......] - ETA: 1s - loss: 0.2993 - accuracy: 0.8719

549/697 [======================>.......] - ETA: 1s - loss: 0.2988 - accuracy: 0.8720

555/697 [======================>.......] - ETA: 1s - loss: 0.2987 - accuracy: 0.8719

561/697 [=======================>......] - ETA: 1s - loss: 0.2994 - accuracy: 0.8717

567/697 [=======================>......] - ETA: 1s - loss: 0.2997 - accuracy: 0.8714

573/697 [=======================>......] - ETA: 1s - loss: 0.2999 - accuracy: 0.8715

579/697 [=======================>......] - ETA: 1s - loss: 0.3000 - accuracy: 0.8714

585/697 [========================>.....] - ETA: 0s - loss: 0.3000 - accuracy: 0.8714

591/697 [========================>.....] - ETA: 0s - loss: 0.3002 - accuracy: 0.8713

597/697 [========================>.....] - ETA: 0s - loss: 0.3002 - accuracy: 0.8711

603/697 [========================>.....] - ETA: 0s - loss: 0.3000 - accuracy: 0.8712

609/697 [=========================>....] - ETA: 0s - loss: 0.2999 - accuracy: 0.8712

615/697 [=========================>....] - ETA: 0s - loss: 0.2999 - accuracy: 0.8712

621/697 [=========================>....] - ETA: 0s - loss: 0.3000 - accuracy: 0.8712

628/697 [==========================>...] - ETA: 0s - loss: 0.2994 - accuracy: 0.8714

635/697 [==========================>...] - ETA: 0s - loss: 0.2990 - accuracy: 0.8715

641/697 [==========================>...] - ETA: 0s - loss: 0.2992 - accuracy: 0.8713

647/697 [==========================>...] - ETA: 0s - loss: 0.2990 - accuracy: 0.8714

654/697 [===========================>..] - ETA: 0s - loss: 0.2989 - accuracy: 0.8714

660/697 [===========================>..] - ETA: 0s - loss: 0.2989 - accuracy: 0.8713

666/697 [===========================>..] - ETA: 0s - loss: 0.2986 - accuracy: 0.8713

672/697 [===========================>..] - ETA: 0s - loss: 0.2988 - accuracy: 0.8711

678/697 [============================>.] - ETA: 0s - loss: 0.2988 - accuracy: 0.8709

684/697 [============================>.] - ETA: 0s - loss: 0.2992 - accuracy: 0.8707

690/697 [============================>.] - ETA: 0s - loss: 0.2989 - accuracy: 0.8707

696/697 [============================>.] - ETA: 0s - loss: 0.2993 - accuracy: 0.8704

697/697 [==============================] - 9s 13ms/step - loss: 0.2993 - accuracy: 0.8704 - val_loss: 0.3697 - val_accuracy: 0.8320


Epoch 3/3


  1/697 [..............................] - ETA: 0s - loss: 0.2157 - accuracy: 0.9531

  7/697 [..............................] - ETA: 5s - loss: 0.2160 - accuracy: 0.9152

 13/697 [..............................] - ETA: 5s - loss: 0.2197 - accuracy: 0.9062

 19/697 [..............................] - ETA: 5s - loss: 0.2118 - accuracy: 0.9112

 25/697 [>.............................] - ETA: 5s - loss: 0.2166 - accuracy: 0.9081

 31/697 [>.............................] - ETA: 5s - loss: 0.2168 - accuracy: 0.9093

 37/697 [>.............................] - ETA: 5s - loss: 0.2114 - accuracy: 0.9117

 44/697 [>.............................] - ETA: 5s - loss: 0.2114 - accuracy: 0.9126

 50/697 [=>............................] - ETA: 5s - loss: 0.2124 - accuracy: 0.9125

 56/697 [=>............................] - ETA: 5s - loss: 0.2153 - accuracy: 0.9104

 62/697 [=>............................] - ETA: 5s - loss: 0.2148 - accuracy: 0.9113

 68/697 [=>............................] - ETA: 5s - loss: 0.2129 - accuracy: 0.9120

 74/697 [==>...........................] - ETA: 5s - loss: 0.2156 - accuracy: 0.9113

 80/697 [==>...........................] - ETA: 5s - loss: 0.2137 - accuracy: 0.9121

 86/697 [==>...........................] - ETA: 5s - loss: 0.2126 - accuracy: 0.9122

 92/697 [==>...........................] - ETA: 5s - loss: 0.2131 - accuracy: 0.9117

 98/697 [===>..........................] - ETA: 5s - loss: 0.2140 - accuracy: 0.9098

104/697 [===>..........................] - ETA: 5s - loss: 0.2162 - accuracy: 0.9090

110/697 [===>..........................] - ETA: 5s - loss: 0.2151 - accuracy: 0.9094

116/697 [===>..........................] - ETA: 5s - loss: 0.2167 - accuracy: 0.9085

122/697 [====>.........................] - ETA: 4s - loss: 0.2177 - accuracy: 0.9082

128/697 [====>.........................] - ETA: 4s - loss: 0.2171 - accuracy: 0.9086

134/697 [====>.........................] - ETA: 4s - loss: 0.2168 - accuracy: 0.9083

140/697 [=====>........................] - ETA: 4s - loss: 0.2178 - accuracy: 0.9083

146/697 [=====>........................] - ETA: 4s - loss: 0.2183 - accuracy: 0.9084

152/697 [=====>........................] - ETA: 4s - loss: 0.2185 - accuracy: 0.9080

158/697 [=====>........................] - ETA: 4s - loss: 0.2199 - accuracy: 0.9072

164/697 [======>.......................] - ETA: 4s - loss: 0.2198 - accuracy: 0.9069

170/697 [======>.......................] - ETA: 4s - loss: 0.2205 - accuracy: 0.9064

176/697 [======>.......................] - ETA: 4s - loss: 0.2184 - accuracy: 0.9074

182/697 [======>.......................] - ETA: 4s - loss: 0.2190 - accuracy: 0.9069

188/697 [=======>......................] - ETA: 4s - loss: 0.2173 - accuracy: 0.9077

194/697 [=======>......................] - ETA: 4s - loss: 0.2159 - accuracy: 0.9083

200/697 [=======>......................] - ETA: 4s - loss: 0.2153 - accuracy: 0.9081

206/697 [=======>......................] - ETA: 4s - loss: 0.2155 - accuracy: 0.9081

212/697 [========>.....................] - ETA: 4s - loss: 0.2158 - accuracy: 0.9077

218/697 [========>.....................] - ETA: 4s - loss: 0.2155 - accuracy: 0.9083

224/697 [========>.....................] - ETA: 4s - loss: 0.2158 - accuracy: 0.9081

230/697 [========>.....................] - ETA: 4s - loss: 0.2163 - accuracy: 0.9077

236/697 [=========>....................] - ETA: 4s - loss: 0.2167 - accuracy: 0.9075

243/697 [=========>....................] - ETA: 3s - loss: 0.2156 - accuracy: 0.9080

249/697 [=========>....................] - ETA: 3s - loss: 0.2168 - accuracy: 0.9074

256/697 [==========>...................] - ETA: 3s - loss: 0.2157 - accuracy: 0.9077

262/697 [==========>...................] - ETA: 3s - loss: 0.2152 - accuracy: 0.9080

269/697 [==========>...................] - ETA: 3s - loss: 0.2173 - accuracy: 0.9068

275/697 [==========>...................] - ETA: 3s - loss: 0.2181 - accuracy: 0.9066

281/697 [===========>..................] - ETA: 3s - loss: 0.2193 - accuracy: 0.9059

287/697 [===========>..................] - ETA: 3s - loss: 0.2195 - accuracy: 0.9059

293/697 [===========>..................] - ETA: 3s - loss: 0.2208 - accuracy: 0.9050

299/697 [===========>..................] - ETA: 3s - loss: 0.2210 - accuracy: 0.9050

305/697 [============>.................] - ETA: 3s - loss: 0.2220 - accuracy: 0.9043

311/697 [============>.................] - ETA: 3s - loss: 0.2220 - accuracy: 0.9045

317/697 [============>.................] - ETA: 3s - loss: 0.2222 - accuracy: 0.9043

323/697 [============>.................] - ETA: 3s - loss: 0.2219 - accuracy: 0.9047

329/697 [=============>................] - ETA: 3s - loss: 0.2220 - accuracy: 0.9046

335/697 [=============>................] - ETA: 3s - loss: 0.2228 - accuracy: 0.9042

341/697 [=============>................] - ETA: 3s - loss: 0.2229 - accuracy: 0.9042

347/697 [=============>................] - ETA: 3s - loss: 0.2228 - accuracy: 0.9044

353/697 [==============>...............] - ETA: 2s - loss: 0.2235 - accuracy: 0.9043

359/697 [==============>...............] - ETA: 2s - loss: 0.2244 - accuracy: 0.9039

365/697 [==============>...............] - ETA: 2s - loss: 0.2247 - accuracy: 0.9038

371/697 [==============>...............] - ETA: 2s - loss: 0.2247 - accuracy: 0.9037

378/697 [===============>..............] - ETA: 2s - loss: 0.2254 - accuracy: 0.9033

385/697 [===============>..............] - ETA: 2s - loss: 0.2253 - accuracy: 0.9032

391/697 [===============>..............] - ETA: 2s - loss: 0.2256 - accuracy: 0.9028

397/697 [================>.............] - ETA: 2s - loss: 0.2259 - accuracy: 0.9027

403/697 [================>.............] - ETA: 2s - loss: 0.2261 - accuracy: 0.9026

409/697 [================>.............] - ETA: 2s - loss: 0.2268 - accuracy: 0.9023

415/697 [================>.............] - ETA: 2s - loss: 0.2271 - accuracy: 0.9022

421/697 [=================>............] - ETA: 2s - loss: 0.2264 - accuracy: 0.9025

427/697 [=================>............] - ETA: 2s - loss: 0.2258 - accuracy: 0.9028

433/697 [=================>............] - ETA: 2s - loss: 0.2257 - accuracy: 0.9027

439/697 [=================>............] - ETA: 2s - loss: 0.2255 - accuracy: 0.9028

445/697 [==================>...........] - ETA: 2s - loss: 0.2255 - accuracy: 0.9027

451/697 [==================>...........] - ETA: 2s - loss: 0.2253 - accuracy: 0.9027

457/697 [==================>...........] - ETA: 2s - loss: 0.2260 - accuracy: 0.9023

463/697 [==================>...........] - ETA: 2s - loss: 0.2258 - accuracy: 0.9023

469/697 [===================>..........] - ETA: 1s - loss: 0.2254 - accuracy: 0.9026

475/697 [===================>..........] - ETA: 1s - loss: 0.2256 - accuracy: 0.9024

481/697 [===================>..........] - ETA: 1s - loss: 0.2256 - accuracy: 0.9024

487/697 [===================>..........] - ETA: 1s - loss: 0.2257 - accuracy: 0.9025

493/697 [====================>.........] - ETA: 1s - loss: 0.2263 - accuracy: 0.9023

499/697 [====================>.........] - ETA: 1s - loss: 0.2270 - accuracy: 0.9019

506/697 [====================>.........] - ETA: 1s - loss: 0.2276 - accuracy: 0.9013

512/697 [=====================>........] - ETA: 1s - loss: 0.2270 - accuracy: 0.9018

518/697 [=====================>........] - ETA: 1s - loss: 0.2273 - accuracy: 0.9017

524/697 [=====================>........] - ETA: 1s - loss: 0.2272 - accuracy: 0.9017

530/697 [=====================>........] - ETA: 1s - loss: 0.2270 - accuracy: 0.9018

536/697 [======================>.......] - ETA: 1s - loss: 0.2269 - accuracy: 0.9020

542/697 [======================>.......] - ETA: 1s - loss: 0.2265 - accuracy: 0.9021

548/697 [======================>.......] - ETA: 1s - loss: 0.2270 - accuracy: 0.9020

554/697 [======================>.......] - ETA: 1s - loss: 0.2276 - accuracy: 0.9017

560/697 [=======================>......] - ETA: 1s - loss: 0.2272 - accuracy: 0.9020

566/697 [=======================>......] - ETA: 1s - loss: 0.2273 - accuracy: 0.9018

572/697 [=======================>......] - ETA: 1s - loss: 0.2269 - accuracy: 0.9020

578/697 [=======================>......] - ETA: 1s - loss: 0.2273 - accuracy: 0.9018

584/697 [========================>.....] - ETA: 0s - loss: 0.2277 - accuracy: 0.9014

591/697 [========================>.....] - ETA: 0s - loss: 0.2282 - accuracy: 0.9013

597/697 [========================>.....] - ETA: 0s - loss: 0.2279 - accuracy: 0.9015

603/697 [========================>.....] - ETA: 0s - loss: 0.2281 - accuracy: 0.9015

609/697 [=========================>....] - ETA: 0s - loss: 0.2282 - accuracy: 0.9014

615/697 [=========================>....] - ETA: 0s - loss: 0.2286 - accuracy: 0.9011

621/697 [=========================>....] - ETA: 0s - loss: 0.2285 - accuracy: 0.9010

627/697 [=========================>....] - ETA: 0s - loss: 0.2286 - accuracy: 0.9011

633/697 [==========================>...] - ETA: 0s - loss: 0.2289 - accuracy: 0.9010

639/697 [==========================>...] - ETA: 0s - loss: 0.2290 - accuracy: 0.9011

645/697 [==========================>...] - ETA: 0s - loss: 0.2290 - accuracy: 0.9011

651/697 [===========================>..] - ETA: 0s - loss: 0.2292 - accuracy: 0.9011

657/697 [===========================>..] - ETA: 0s - loss: 0.2288 - accuracy: 0.9014

663/697 [===========================>..] - ETA: 0s - loss: 0.2286 - accuracy: 0.9015

669/697 [===========================>..] - ETA: 0s - loss: 0.2292 - accuracy: 0.9011

675/697 [============================>.] - ETA: 0s - loss: 0.2294 - accuracy: 0.9011

681/697 [============================>.] - ETA: 0s - loss: 0.2296 - accuracy: 0.9010

687/697 [============================>.] - ETA: 0s - loss: 0.2299 - accuracy: 0.9009

693/697 [============================>.] - ETA: 0s - loss: 0.2301 - accuracy: 0.9007

697/697 [==============================] - 9s 13ms/step - loss: 0.2303 - accuracy: 0.9006 - val_loss: 0.3776 - val_accuracy: 0.8304


In [23]:
eval_loss, eval_acc = model.evaluate(test_data)

print('\nEval loss: {:.3f}, Eval accuracy: {:.3f}'.format(eval_loss, eval_acc))

      1/Unknown - 0s 13us/step - loss: 0.4187 - accuracy: 0.8438

      4/Unknown - 0s 14ms/step - loss: 0.3489 - accuracy: 0.8750

      7/Unknown - 0s 15ms/step - loss: 0.3641 - accuracy: 0.8571

     10/Unknown - 0s 16ms/step - loss: 0.3744 - accuracy: 0.8531

     13/Unknown - 0s 16ms/step - loss: 0.3859 - accuracy: 0.8462

     16/Unknown - 0s 16ms/step - loss: 0.3992 - accuracy: 0.8438

     19/Unknown - 0s 17ms/step - loss: 0.3928 - accuracy: 0.8421

     23/Unknown - 0s 17ms/step - loss: 0.3932 - accuracy: 0.8417

     26/Unknown - 0s 17ms/step - loss: 0.3947 - accuracy: 0.8389

     29/Unknown - 0s 17ms/step - loss: 0.3867 - accuracy: 0.8432

     32/Unknown - 1s 17ms/step - loss: 0.3937 - accuracy: 0.8359

     35/Unknown - 1s 17ms/step - loss: 0.3838 - accuracy: 0.8375

     38/Unknown - 1s 17ms/step - loss: 0.3845 - accuracy: 0.8372

     41/Unknown - 1s 17ms/step - loss: 0.3851 - accuracy: 0.8342

     44/Unknown - 1s 17ms/step - loss: 0.3924 - accuracy: 0.8317

     47/Unknown - 1s 17ms/step - loss: 0.3888 - accuracy: 0.8324

     50/Unknown - 1s 17ms/step - loss: 0.3905 - accuracy: 0.8309

     53/Unknown - 1s 17ms/step - loss: 0.3906 - accuracy: 0.8290

     56/Unknown - 1s 17ms/step - loss: 0.3854 - accuracy: 0.8298

     59/Unknown - 1s 17ms/step - loss: 0.3857 - accuracy: 0.8289

     62/Unknown - 1s 17ms/step - loss: 0.3837 - accuracy: 0.8291

     65/Unknown - 1s 17ms/step - loss: 0.3787 - accuracy: 0.8310

     68/Unknown - 1s 17ms/step - loss: 0.3794 - accuracy: 0.8304

     71/Unknown - 1s 17ms/step - loss: 0.3790 - accuracy: 0.8303

     74/Unknown - 1s 17ms/step - loss: 0.3804 - accuracy: 0.8300

     77/Unknown - 1s 17ms/step - loss: 0.3788 - accuracy: 0.8302

79/79 [==============================] - 1s 18ms/step - loss: 0.3776 - accuracy: 0.8304



Eval loss: 0.378, Eval accuracy: 0.830
